cannon:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  


  piston_controller:
    type: position_controllers/JointPositionController
    joint: piston_move
    pid: {p: 100.0, i: 0.01, d: 10.0}


